[[bars]]
name = "bar-left"
monitor = "DP-1"
pos_x = 0
pos_y = 1060

modules_left = ["I3"]
modules_right = ["Clock","Pulse","Mpris"]

[[bars]]
name = "bar-right"
monitor = "HDMI-0"
pos_x = 1920
pos_y = 1060

modules_left = ["I3"]
modules_right = ["Clock","Pulse","Mpris"]
